apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app-container
        image: rookie7722/express-app:befa162e7357cc9eabd7ccbd09a5d17c911cf977
        imagePullPolicy: Always